version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Docker build started on `date`
      - docker-compose up -d
      - docker-compose exec -T php-apache /bin/bash -c "composer install"
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - echo Wait to compose up completed..
      - sleep 30
  build:
    commands:
      - docker-compose exec -T php-apache /bin/bash -c "php artisan migrate --env=testing --force"
      - docker-compose exec -T php-apache /bin/bash -c "php artisan db:seed --env=testing --force"
      - echo Test started on `date`
      - docker-compose exec -T php-apache /bin/bash -c "composer test"
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - sed -i -e "s/AWS_ACCOUNT_ID/$AWS_ACCOUNT_ID/g" Dockerrun.aws.json
      - sed -i -e "s/TAG/$IMAGE_TAG/g" Dockerrun.aws.json
reports:
  report-name-or-arn:
    files:
      - reports/report.xml
artifacts:
  files:
    - .ebextensions/*
    - Dockerrun.aws.json
